### ISSUE TITLE
Does opt-SNE support FIt-SNE besides BH-SNE?

### ISSUE THREAD

**Issue by JPGranizo** [milescsmith/ReductionWrappers#2]
Hi,

I was wondering if opt-SNE also supports FIt-SNE besides BH-SNE implementation?
Which other methods are possible besides method = "barnes_hut"?

Thank you,
Kind regards
Jo

**Comment by milescsmith** [comment]
Hi,

The opt-SNE here is just a wrapper around the Python [Multicore-opt-SNE](https://github.com/omiq-ai/Multicore-opt-SNE) module and thus only has the functionality provided it.  Looking at the opt-SNE code, it looks like the `method` parameter is actually unused so I think it is stuck using the Barnes-Hut implementation.
