### ISSUE TITLE
cannot install the package

### ISSUE THREAD

**Issue by tn00992786** [milescsmith/ReductionWrappers#6]
Hello, do you know how to solve this?

> remotes::install_github("milescsmith/dim.reduction.wrappers")
Downloading GitHub repo milescsmith/dim.reduction.wrappers@HEAD
Error: Failed to install 'ReductionWrappers' from GitHub:
  Git does not seem to be installed on your system.

thanks!

**Comment by milescsmith** [comment]
Install git?
